namespace MCAPAPI.Models
{
    public class Trades
    {

        public string tno { get; set; }
        public string src_cd { get; set; }
        public string trd_process_ind { get; set; }
        public string entry_type { get; set; }
        public string trd_type { get; set; }
        public string system_dt { get; set; }
        public string entry_dt { get; set; }
        public string trade_dt { get; set; }
        public string settle_dt { get; set; }
        public string avail_dt { get; set; }
        public string exec_dt { get; set; }
        public string symbol { get; set; }
        public string sym_no { get; set; }
        public string qty { get; set; }
        public string price { get; set; }
        public string g_amt { get; set; }
        public string n_amt { get; set; }
        public string comm { get; set; }
        public string sec_fee { get; set; }
        public string exch_fee { get; set; }
        public string clr_fee { get; set; }
        public string ecn_fee { get; set; }
        public string brk_fee { get; set; }
        public string occ_fee { get; set; }
        public string oth_fee { get; set; }
        public string sec_fee2 { get; set; }
        public string tefra_fee { get; set; }
        public string m_fee1_cd { get; set; }
        public string m_fee1_dbcr { get; set; }
        public string m_fee1 { get; set; }
        public string m_fee2_cd { get; set; }
        public string m_fee2_dbcr { get; set; }
        public string m_fee2 { get; set; }
        public string m_fee3_cd { get; set; }
        public string m_fee3_dbcr { get; set; }
        public string m_fee3 { get; set; }
        public string m_fee4_cd { get; set; }
        public string m_fee4_dbcr { get; set; }
        public string m_fee4 { get; set; }
        public string m_fee5_cd { get; set; }
        public string m_fee5_dbcr { get; set; }
        public string m_fee5 { get; set; }
        public string m_fee6_cd { get; set; }
        public string m_fee6_dbcr { get; set; }
        public string m_fee6 { get; set; }
        public string memo_fee1_cd { get; set; }
        public string memo_fee1 { get; set; }
        public string memo_fee2_cd { get; set; }
        public string memo_fee2 { get; set; }
        public string memo_fee3_cd { get; set; }
        public string memo_fee3 { get; set; }
        public string corr { get; set; }
        public string office { get; set; }
        public string acct_no { get; set; }
        public string acct_type { get; set; }
        public string sub_acct_no { get; set; }
        public string contra_code { get; set; }
        public string contra_corr { get; set; }
        public string contra_office { get; set; }
        public string contra_acct_no { get; set; }
        public string contra_acct_type { get; set; }
        public string contra_sub_acct_no { get; set; }
        public string blot_exch_cd { get; set; }
        public string blot_clr_typ { get; set; }
        public string blot_method { get; set; }
        public string err_load { get; set; }
        public string err_mesg { get; set; }
        public string batchno { get; set; }
        public string capacity { get; set; }
        public string sol_unsol { get; set; }
        public string trd_tag { get; set; }
        public string descr { get; set; }
        public string loginid { get; set; }
        public string sec_type { get; set; }
        public string asset_type { get; set; }
        public string sec_no { get; set; }
        public string buy_interest { get; set; }
        public string finc_yield { get; set; }
        public string yield_type { get; set; }
        public string settle_days { get; set; }
        public string tr_no { get; set; }
        public string memo1 { get; set; }
        public string memo2 { get; set; }
        public string tax_lot { get; set; }
        public string rr_cd { get; set; }
        public string ad_cd { get; set; }
        public string an_cd { get; set; }
        public string tr_cd { get; set; }
        public string g_lot_amt { get; set; }
        public string n_lot_amt { get; set; }
        public string currency1 { get; set; }
        public string curr_rate { get; set; }
        public string order_type { get; set; }
        public string liquidity { get; set; }
        public string exec_exch { get; set; }
        public string ac_grp_cd { get; set; }
        public string trailer_codes { get; set; }
        public string set_currency { get; set; }
        public string set_country { get; set; }
        public string set_location { get; set; }
        public string np_fee1_cd { get; set; }
        public string np_fee1 { get; set; }
        public string np_fee2_cd { get; set; }
        public string np_fee2 { get; set; }
        public string np_fee3_cd { get; set; }
        public string np_fee3 { get; set; }
        public string rptd_price { get; set; }
        public string sales_credit { get; set; }
        public string discretion_flg { get; set; }
        public string ira_year { get; set; }
        public string ira_tax_cd { get; set; }
        public string ira_fed_tax { get; set; }
        public string ira_st_tax { get; set; }
        public string lot_tr_no { get; set; }
        public string commflag { get; set; }
        public string raw_comm { get; set; }
        public string tag_70E { get; set; }
        public string ira_st_cd { get; set; }
        public string cov_uncov { get; set; }
        public string memo3 { get; set; }
        public string cl_order_id { get; set; }
        public string order_id { get; set; }
        public string exec_id { get; set; }
        public string finc_discount { get; set; }
        public string finc_spread { get; set; }
        public string price_source { get; set; }
        public string factor { get; set; }
        public string factor_dt { get; set; }
        public string delivery_dt { get; set; }
        public string dvp_SMartLoan { get; set; }
        public string repo_rate { get; set; }

        
    }
}

